import { App } from "./app";
import { IPageBase } from "./models/pageBase";
import { IGalleryData } from "./models/gallery.model";
export declare class Gallery implements IPageBase {
    private _app;
    private _galleryData;
    private _pointerDownTarget;
    private _pointerStart;
    private _pointerDiffStart;
    private _diffX;
    private _diffY;
    private _uniforms;
    private _widthRest;
    private _heightRest;
    private _centerX;
    private _centerY;
    private _rects;
    private _mouseIsHeldDown;
    private _sprites;
    private _borders;
    private _hoveredImageUrl;
    private _galleryContainer;
    private imageMouseOverHandlers;
    private imageMouseOutHandlers;
    private onBackClicked;
    constructor(_app: App, _galleryData: IGalleryData);
    init(): void;
    update(): void;
    initShaders(): void;
    private initEvents;
    private onDragPointerDown;
    private onDragPointerUp;
    private onDragPointerMove;
    private initGrid;
    private initNavigation;
    private initRectsAndImages;
    clean(): void;
    goToMainPage(): void;
    destroy(): void;
}
